name: Publish

on:
  push:
    branches:
      - master
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org/'

      - run: npm ci
      - name: Tag canary version
        if: github.ref_name == 'develop'
        run: npm version prerelease --preid=canary-$(git rev-parse --short HEAD) --no-git-tag-version

      - name: build
        run: npm run build
      - uses: JS-DevTools/npm-publish@v3
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ github.ref_name == 'master' && 'latest' || github.ref_name == 'develop' && 'next' }}
